### PR TITLE
Adds citation for shuffling theorem

### PR DESCRIPTION
**Pull request by jerry-james**

### CODE REVIEW

**Comment by stamourv** [comment]
Merged, thanks!

**Comment by stamourv** [comment]
I just looked at the paper a bit, and while it looks like the right citation, it looks like the docs have the wrong bound. Instead of 7, it should be about 12 + theta, according to the abstract. I assume you know the area better then I do, can you confirm which one is right?

**Comment by jerry-james** [comment]
That is a dangerous assumption! Hah! But as I understand it "seven is sufficient" is the the popular take-away from the paper rather than provable mathematical fact.  The result of the 3/2log2n equation for n=52 and theta=0 is ~8.55, but if a deck is perfectly shuffled 8 times it will be back in its original state! So this combined with the variation distance of seven shuffles being good enough is why "seven is sufficient".

**Comment by rfindler** [comment]
Thank you!

**Pull request closed without merging**
